Vagrant.configure("2") do |config|
    config.vm.box = "onlyoffice/base-debian13"
    config.vm.box_version = "1.0.0"

    config.vm.define "noleclerS" do |server|
        server.vm.hostname = "noleclerS"
        server.vm.boot_timeout = 600
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
        end
        server.vm.provision "shell", path: "scripts/server.sh"
    end
end