Vagrant.configure("2") do |config|
    config.vm.box = "onlyoffice/base-debian13"
    config.vm.box_version = "1.0.0"

#============================FIRST VM==============================
    config.vm.define "noleclerS" do |server|
        server.vm.hostname = "noleclerS"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "noleclerS"]
            v.memory = 1024
            v.cpus = 1
        end
        server.vm.provision "shell", path: "scripts/server.sh"
    end

#============================SECOND VM==============================
    config.vm.define "noleclerSW" do |worker|
        worker.vm.hostname = "noleclerSW"
        worker.vm.network "private_network", ip: "192.168.56.111"

        worker.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "noleclerSW"]
            v.memory = 1024
            v.cpus = 1
        end
        worker.vm.provision "shell", path: "scripts/worker.sh"
    end
end
